CREATE OR REPLACE STREAM "TOP_VIEWS_BOOKS" (ISBN VARCHAR(16), CNT BIGINT);
CREATE OR REPLACE PUMP "TOP_VIEWS_BOOKS_PUMP" AS INSERT INTO "TOP_VIEWS_BOOKS"
SELECT STREAM "ISBN",CNT FROM
(SELECT STREAM DISTINCT "ISBN", COUNT(*) as CNT
FROM "SOURCE_SQL_STREAM_001"
GROUP BY "ISBN", STEP("SOURCE_SQL_STREAM_001".ROWTIME BY INTERVAL '60' SECOND)
ORDER BY CNT DESC) WHERE CNT>20 LIMIT 10;
-- #######
-- ####### Current version is working
CREATE OR REPLACE STREAM "TOP_VIEWS_BOOKS" (ISBN VARCHAR(16), MOST_FREQUENT_VALUES BIGINT);
CREATE OR REPLACE PUMP "TOP_VIEWS_BOOKS_PUMP" AS INSERT INTO "TOP_VIEWS_BOOKS"
SELECT STREAM *
        FROM TABLE (TOP_K_ITEMS_TUMBLING(
            CURSOR(SELECT STREAM * FROM "SOURCE_SQL_STREAM_001"),
            'ISBN',20,60));